### ISSUE TITLE
Diskussion: Name des Projekts

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/Info#1]
Friends Of REDAXO heißt es aktuell in Anlehnung an z. B. [FriendsOfSymfony](https://github.com/FriendsOfSymfony) oder [FriendsOfPHP](https://github.com/FriendsOfPHP). Es gab ein paar weitere Vorschläge, etwa:

- REDAXO Commons
- REDAXO Devs
- REDAXO Team
- REDAXO Folks
- REDAXO Leaks, … Cracks, … Hacks, … Frogs, …

Falls jemandem ein besserer Name als Friends Of REDAXO einfällt, macht jederzeit Vorschläge! Andernfalls kann das Ticket hier auch gern wieder geschlossen werden ;)

**Comment by staabm** [comment]
Ich finde den namen gut

**Comment by schuer** [comment]
Der Name hat sich in der Zwischenzeit im Team etabliert. Also belassen wir ihn wohl dabei.
Wer Einwände hat, öffnet das Ticket wieder :)
