### ISSUE TITLE
Addon: Pagination

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/Info#10]
_From @schuer on May 23, 2016 12:35_

Wurde heute im Chat diskutiert: Ein generischer Paginierungs-Helfer wäre sehr nützlich. Immer dann, wenn Artikellisten ausgegeben werden, die beliebig lang sein können.

Oftmals schreibt man in solchen Fällen Logik in Templates und/oder Module, aber die Implementierung als Addon wäre sicherlich viel sinnvoller. Das Addon könnte diverse Methoden anbieten, mit denen all die Dinge umgesetzt werden können, die man für eine schöne Paginierung benötigt:
- Artikel nach bestimmten Kriterien abfragen (Anzahl, Datum, Autor, Limit, Sortierung, etc.)
- Behandlung der URIs/Querystrings (z. B. `/page-2` oder `?page=2`) mit entsprechender Artikelausgabe
- Helper für `url_prev`, `url_next` und `has_prev`, `has_next` (werden z. B. auch für meta-`rel`-Angaben im <head> benötigt)
- Helper für Anzahl der Artikel und Anzahl der Seiten
- Vielleicht sogar vorgefertigte Fragmente für die Ausgabe der Paginierungselemente (Buttons)

_Copied from original issue: FriendsOfREDAXO/wuensche_ideen#6_

**Comment by alexplusde** [comment]
Wäre auch was für search_it. Hilfe willkommen.

**Comment by schuer** [comment]
Stimmt, Suchergebnisse wären ein typischer Fall für Paginierung, die man besser nur einmal entwickelt, und nicht immer wieder aufs Neue.

**Comment by gharlan** [comment]
Nur als kleine Info: Ein kleines Helferlein für Paginierungen hat der R5-Core dabei: [`rex_pager`](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/util/pager.php)
Bietet aber natürlich nicht alle Features aus dem ersten Post. ;)

Die `rex_pager`-Klasse wird zum Beispiel von der `rex_list` und auch in der Struktur im Backend verwendet.
Auch das neue Mini-ORM in yform arbeitet mit der Klasse zusammen. Ich sehe allerdings ein, dass ich da mal Beispiele bereitstellen muss, damit dass dann auch mal jemand verwendet.. ;)

Ein Fragment für die Klasse gibt es übrigens auch: [pagination.php](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/fragments/core/navigations/pagination.php)

**Comment by alexplusde** [comment]
@gharlan du hast den Job! ;)

**Comment by staabm** [comment]
Gefühlt sind das für mich keine use cases für ein addon. Sowas kann man mit 1-2 klassen realisieren.
Wenn man diese mini-use-cases alle in separaten addons realisiert hat man am schluss sehr viele addons in der installation.
Klongt nach 2 klassen die man via projekt-addon in seine seite bringen könnte.

**Comment by tbaddade** [comment]
Wenn man das Eloquent Addon einsetzt kann man sich dort auch eine Pagination erstellen lassen. Ich hatte das mal in R4 direkt für rex_sql aufgesetzt.

**Comment by alexplusde** [comment]
Wäre auf der anderen Seite auch ein tolles Beispiel dafür, wie man Fragmente in Redaxo benutzt... Das würde ich gerne bspw. daran lernen.

**Comment by skerbis** [comment]
@gharlan ein Beispiel wär schon mal was für den Start 👍

**Comment by alexplusde** [comment]
Beispiel bei "tricks". close?
