### ISSUE TITLE
Addon: Backend-"Mutter-AddOn"

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/Info#12]
_From @polarpixel on May 25, 2016 19:21_

Es gab die Idee schon bei Redaxo 4 hin und wieder:
Ich fände es gut, wenn es für kleine Backend-Helferlein-AddOns ein Mutter-AddOn gäbe, so dass sich diese als Plugin in das AddOn einklinken könnten. Das würde die AddOn-Verwaltung übersichtlicher machen, und im Idealfall würde das Mutter-Addon sogar bestimmte, oft benötigte Funktionalitäten bereitstellen, so dass die Plugins diese mit minimalem Aufwand nutzen könnten, z.B. CSS- oder JS-Dateien laden, etc.

Beispiele für diese kleinen Backend-AddOns wären Sachen wie (man könnte die Liste lange fortsetzen):
- Selectfeld-Replacements wie Harvesthq / Select2
- Datepicker / Iconpicker
- Redaxo-Logo gegen Kunden-Logo ersetzen
- einige der Plugins von oliens Out5-AddOn würden hier auch reinpassen.

_Copied from original issue: FriendsOfREDAXO/wuensche_ideen#8_

**Comment by schuer** [comment]
_From @olien on May 28, 2016 18:49_

Habe out5 hierhin übertragen... https://github.com/FriendsOfREDAXO/out5

**Comment by schuer** [comment]
… und einen Screenshot in die README bekommen :)

**Comment by schuer** [comment]
_From @olien on May 28, 2016 20:9_

Top

**Comment by schuer** [comment]
Frage in die Runde: Ist dieses Issue nun erfüllt durch die inzwischen verfügbaren Addons?

* Das in REX 5.2 enthaltene __project-Addon__
* Das [theme-Addon](https://github.com/FriendsOfREDAXO)

**Comment by polarpixel** [comment]
Aus meiner Sicht ist es erledigt. Danke fürs Wiederaufnehmen des Fadens.

**Comment by skerbis** [comment]
Datepicker? Wo gibt es den? ... her damit

**Comment by DanielWeitenauer** [comment]
Hi,
@tgoellner wollte das glÖbals-Addon zu einem Theme-Plugin umschreiben und hat in dem Zug schon eine Anpassung für die Plugin-Fähigkeit vorgenommen. Da könnten also beliebig Plugins eingebunden werden.

**Comment by DanielWeitenauer** [comment]
Aber wäre das nicht eher ein be_style Thema?

**Comment by schuer** [comment]
Erledigt. Falls nicht, bitte wieder öffnen.
