### ISSUE TITLE
Unter welcher Lizenz veröffentlichen wir die Addons?

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/Info#15]
Ich denke, wir sollten uns auf eine einigen. Hatten da letztens schon mal drüber geschrieben in Slack, aber so richtig festgehalten hatten wir es glaube ich noch nicht, daher hier nun nochmal "offiziell" als Issue.

Ich hatte MIT vorgeschlagen, da Redaxo selbst auch unter MIT steht.
@olien hatte bei aufgaben eigentlich die Beerware drin, @tbaddade nun in quick_navigation auch: https://github.com/FriendsOfREDAXO/quick_navigation/blob/master/LICENSE.md
Weitere Idee von @tbaddade war eine `T-REX-Burger License`. :D

**Comment by DanielWeitenauer** [comment]
Ich finde MIT OK.

**Comment by schuer** [comment]
+1 MIT.

**Comment by tbaddade** [comment]
Ich bin für die Beerware Lizenz. 

Ohne diese hätte es wahrscheinlich keine Bierrunden zum REDAXO Tag gegeben. Auch wenn @palber die Lizenzen zu Frau Schultze oder Watson nicht wahrgenommen hat, war es doch etwas Schönes für die Kehle. 

Bei der MIT kommt gar nix bei rum. Tsts

**Comment by palber** [comment]
Ich bin auch für beerware.

Da man sich ja doch das ein oder andere mal trifft, wäre ich auf jeden fall bereit ein, zwei Bierchen zu spendieren ;) 

Ist finde es ist ne nette Möglichkeit seine dankbarkeit zu zeige. In diesem Sinne: Danke @tbaddade

**Comment by dergel** [comment]
T-REX-Burger License
cool :) .. 

vielleicht eine duale/triale Lizenz :) .. man kann sich aussuchen ob egoistische MIT Lizenz. oder T-REX-Burger (extended MIT) oder Beerlizenz (extended MIT)

**Comment by olien** [comment]
SO?



_ADDONNAME_ - Beerware and T-REX-Burger License

"THE BEER-WARE and T-REX-Burger LICENSE" (Revision 42): friendsof@redaxo.org wrote this addon. As long as you retain this notice you can do whatever you want with this stuff. If we meet some day, and you think this stuff is worth it, you can buy us a beer and / or a T-REX-Burger in return. Friends Of REDAXO

"THE BEER-WARE and T-REX-Burger LICENSE" (Revision 42): friendsof@redaxo.org schrieb dieses AddOn. Solange Sie diesen Vermerk nicht entfernen, können Sie mit dem Material machen, was Sie möchten. Wenn wir uns eines Tages treffen und Sie denken, das Material ist es wert, können Sie uns dafür ein Bier und / oder einen T-REX-Burger ausgeben. Friends Of REDAXO

**Comment by polarpixel** [comment]
Ich find das super. Dann ist alles nicht so bier"-ernst.

**Comment by schuer** [comment]
Ich mag weder Bier noch Burger, finde es aber auch okay so.

**Comment by tbaddade** [comment]
> Ich mag weder Bier noch Burger

Dann kommt noch eine *Coffeeware License* mit rein oder du suchst noch was anderes aus :)

**Comment by phoebusryan** [comment]
Sind wir uns da jetzt einig und fügen das überall ein? Ich passe mich auf jeden Fall euch an.

**Comment by dergel** [comment]
Mir wäre wichtig, dass bei den Beer und TREX Lizenzen auch die MIT Lizenz gesetzt wird - damit klar ist, dass man damit frei umgehen darf..

**Comment by tbaddade** [comment]
> damit klar ist, dass man damit frei umgehen darf

Steht doch eindeutig im Text.

**Comment by staabm** [comment]
> Steht doch eindeutig im Text.
Ich denke nicht dass die texte wie oben beschrieben rechtlich eindeutig/perfekt sind daher würde ich auch unbeding die MIT Lizenz bennen. Damit wissen die Leute auch umzugehen.

**Comment by phoebusryan** [comment]
Sind wir uns hier nun eigentlich einig geworden?

**Comment by schuer** [comment]
Ist jetzt das Fazit, dass wir aufgrund rechtlicher Überlegungen unbedingt MIT verwenden, und diese — wer möchte — dann aber um Bier, Burger und Kaffee erweitern, sprich: am Ende dazuschreiben?

Möchte jemand Beispiele hier hinterlegen?
Kann das Ticket geschlossen werden?

**Comment by alexplusde** [comment]
Kein Widerspruch. Bitte um einen entsprechenden Textbaustein im Info-Repo.

**Comment by alexplusde** [comment]
@schuer könntest du die Repos jeweils um die MIT-Lizenz ergänzen (Readme/Addon-Hilfedatei) und im Info-Repo darauf hinweisen, dass die Lizenz in jedes FOR-Projekt gehört?

**Comment by schuer** [comment]
Habe die Repos, die ich bereits auf der Platte hatte, um die MIT-Lizenz ergänzt. Für die anderen fehlte mir die Lust ;)

**Comment by alexplusde** [comment]
Danke!

**Comment by schuer** [comment]
Nochmal ein Nachtrag: Habe nun auch die restlichen Repos ergänzt, weil ich gesehen hatte, dass Github es einem einfach macht. Man kann direkt in der Weboberfläche eine Lizenzdatei hinzufügen und für diese direkt eine Vorlage, z. b. MIT, auswählen. Sehr cool.

Problem mit den »gemischten« Lizenzen wie in der Diskussion oben besprochen: Github erkennt die Lizenz nur eigenständig, wenn sie sauber ist. Sobald man den MIT-Text zum Beispiel um Beer-Ware ergänzt, wie es Thomas etwa beim Quick-Navigation-Addon haben wollte, wird MIT leider nicht mehr erkannt.
Deshalb die Empfehlung: MIT immer sauber hinzufügen, und **wer noch Bier, Kaffee oder Burger zusätzlich drin haben möchte, legt am besten eine zusätzliche Datei an oder klärt das direkt in der README.** Das ist auch der Weg, den Github vorschlägt: https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by tbaddade** [comment]
Finde ich nicht wirklich gut … Scheint aber die Masse so zu wollen.

**Comment by alexplusde** [comment]
Ich spendiere ggf. ein Trost-Bier, wäre das ok? @tbaddade

**Comment by dergel** [comment]
Das mit der MIT Lizenz ist leider schon sehr wichtig, dass diese eindeutig ist. Gerade Lizenzen wie "macht damit was ihr wollt" ist uneindeutig und ist daher schwierig zu nutzen (manche Firmen verbieten das sogar - **haben gerade selbst den Fall** - ausser man entfernt diese lizenz und übernimmt komplett selbst die Verantwortung dafür) ...

Deswegen fände ich es gut, wenn bei friendsofredaxo **die MIT Lizenz sogar pauschal als Standard festgesetzt** wäre. Quasi - wenn man ein AddOn hier hat - oder ähnliches - muss sich unter MIT liegen. 

Alle anderen Beer, Burger und Co. Ergänzungen würde ich, wie von Dirk vorgeschlagen, in die README packen. Dort kann man das ausschlachten - sollte nur die eigentliche Lizenz nicht in Frage stellen oder "ergänzen" ..
