### ISSUE TITLE
Repo für Snippets?

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/Info#17]
Wäre es sinnvoll eine Repo anzulegen in das jeder seine Snippets hineinwerfen kann?
So hätte man vielleicht ein zentrales Nachschlagewerk an kleinen Dingen die vielleicht jemanden nützlich sind.

Vielleicht sortiert in Ordner je nach Typ.

Was meint ihr?

**Comment by olien** [comment]
Ne gute Idee aber wäre es nicht besser passende Snippets in die Doku einzubauen - oder was meinst du genau?

**Comment by eaCe** [comment]
Bin nicht sicher ob da der Verwaltungsaufand größer wäre.
Dachte so kann man das einfach rein werfen und in Kategorien sortieren. Oder so.. :)

**Comment by olien** [comment]
Also von mir aus sehr gerne..."Sinnvolle" Snippets können zusätzlich in die Doku übernommen werden...

**Comment by alexplusde** [comment]
my 2 cents:
oft gibt's ja für ein und dieselbe Problemstellung verschiedene Lösungsmöglichkeiten. Diese würden nie alle gleichzeitig in einer Doku landen, deshalb wäre ein zentraler Ort für sowas begrüßenswert.

Allerdings sollte man dann ein paar andere Orte (Redaxo-Wiki) dicht machen. Snippets finden sich schließlich schon an diesen Orten:

- Module auf redaxo.org
- Doku auf redaxo.org
- Wiki auf redaxo.org
- Forum auf redaxo.org
- Issues in einzelnen Repos auf Github
- Wiki in einzelnen Repos auf Github
- Innerhalb der Addons (in einer Redaxo-Installation)
- Diskussionen in Slack, per E-Mail, DM, ...

(Was mich an https://xkcd.com/927/ erinnert)

**Comment by alexplusde** [comment]
Viel wichtiger als Snippets wären in meinen Augen kleine How-Tos und Best Practices, was ja Snippets beinhalten kann. Da geht in meinen Augen so viel Know-How auf allen Kanälen verloren.

Bei YForm arbeiten wir ja gerade an einer Doku und @dergel hat eine Struktur aufgebaut, die dann auch im Backend direkt die Doku darstellen kann. 

Idee: Vielleicht könnte FOR eingereichte Snippets sammeln, aufbereiten und dann den Addon-Entwicklern für ihre Addon-Doku zur Verfügung stellen.

**Comment by eaCe** [comment]
Tutorials für Anfänger sind auch gut...

**Comment by eaCe** [comment]
Um das ganze einfacher zu machen, hier ein Vorschlag:

Wir eröffnen ein Snippet Repo das nur eine Readme enthält.
In diese werden Kategorien geschrieben und unter diesen kann jeder Links zu seinen Gist's hinterlegen. Somit ist der Verwaltungsaufwand (push pull merge etc..) geringer und die Hemmschwelle den Kram preiszugeben vielleicht geringer?

**Comment by schuer** [comment]
Dieses Ticket hat sich inzwischen erledigt:
https://github.com/FriendsOfREDAXO/rex5_snippets

(Issue kann bei Bedarf gerne nochmal geöffnet werden.)
