### ISSUE TITLE
Addon: Terminverwaltung

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Info#18]
Hallo Zusammen,

ich habe mir gerade die beiden aktuell für REX5 bestehenden Addons zur Terminverwaltung angesehen. Reichen die oder sollen wir zusammen ein neues entwicklen?

Lasst uns doch mal sammeln was für eine "einfache" Terminverwaltung notwendig ist...

EINGABE / VERWALTUNG

- Kategorien (eigene Verwaltung)
- Titel
- Kurzbeschreibung
- Teaserbild
- Datum
- Ort (eigene Verwaltung)
- Uhrzeit (optional)
- Wiederholen (täglich, wöchentlich, monatlich, jährlich)
- Wiederholen bis (nur wenn "Wiederholen" angegeben)
- Beschreibung
- Bild
- Bildergalerie
- externer Link
- Download von Dokumenten

- Termin kopieren 
- Termin löschen
- Termin "offline"

AUSGABE

- Teaserausgabe (Liste - die nächsten x Termine je nach Kategorie/en gefiltert, Paginierung)
- Kalenderausgabe (optional Link mit .ics Daten)
- evtl. Anmelde- / Anfrageformular mit den Termindaten

**Comment by phoebusryan** [comment]
Ich bin absolut gegen ein weiteres Termin-Addon. 2 sind bereits eines zu viel. Lieber die bestehenden supporten und weiterentwickeln.

**Comment by olien** [comment]
Ok. Dann eine News Verwaltung? Die Daten sind nahezu die gleichen. Der Umgang mit den Daten ist nur ein anderer :-))

**Comment by alexplusde** [comment]
Ergänzend
* Tags

**Comment by phoebusryan** [comment]
@olien Ist dir langweilig und willst unbedingt neue Addons bauen oder warum fragst du das?

**Comment by olien** [comment]
Ich brauche so etwas bestimmt demnächst einmal...

**Comment by staabm** [comment]
Gibt es einen konkreten bedarf oder geht es hier mehr um ein "wäre toll wenn wir eines hätten"?

**Comment by olien** [comment]
Eher "wäre toll wenn wir eines hätten"... Ideen Sammeln etc...

**Comment by olien** [comment]
Ich schliesse das mal hier...

https://github.com/eaCe/rex_calendar

(@phoebusryan sag doch was... :-))

**Comment by eaCe** [comment]
Hab dieses Issue heir noch gar nicht gesehen... :| würde, wenn gewünscht, den kalender hier her ziehen, wenn er denn in einem brauchbarem zustand ist...

**Comment by olien** [comment]
Ich installiere mir den gleich mal... sieht vielversprechend aus!
