### ISSUE TITLE
monatliche Addon-Challenge

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/Info#20]
Nach kurzem Chat mit @schuer dazu, dass wir in FOR doch eher alle für uns arbeiten und nur wenige Addons wirklich in der Community entwickelt werden:

Wir könnten eine monatliche Challenge veranstalten und ein Addon auswählen, dem alle FOR-Mitglieder besondere Aufmerksamkeit schenken, z. B. mit
- Testen und Debuggen
- Vereinheitlichung / QM
- Features/Erweiterungen mit PRs
- Hilfe/Dokumentation 
- Übersetzung in EN

Den Abschluss könnte dann eine Rubrik "Addon des Monats" auf redaxo,org, im Forum und auf Slack bilden, in dem die Neuerungen vorgestellt werden.

Was meint ihr?

**Comment by schuer** [comment]
Ich finde grundsätzlich alle Aktionen sinnvoll, die dafür sorgen, dass FOR mehr ein »wir« wird, und nicht nur ein »ich« bleibt :) Alex’ Idee könnte das sicherlich unterstützen.

**Comment by gharlan** [comment]
Ich finde die Idee wirklich sehr gut!
Ich glaube das könnte die Addons wirklich gut nach vorne bringen, und eben auch das „Wir“ fördern.

**Comment by tbaddade** [comment]
Ich finde die Idee auch super nur würde ich …

> dass wir in FOR doch eher alle für uns arbeiten

 das nicht kommunizieren. Ich fände es gut wenn man gemeinsam entwickelt. Also den Grundgedanken von FOR weiter vorantreibt und eben nicht jeder für sich entwickelt.

**Comment by alexplusde** [comment]
@tbaddade da habe ich mich wohl missverständlich ausgedrückt. Eben das ist das Ziel einer solchen Aktion: Gemeinsam etwas voranbringen, sich die Bälle zuspielen und sich hinterher auf die Schulter klopfen können :)

**Comment by alexplusde** [comment]
Was meinen die anderen dazu?

@aeberhard
@alexwenz
@alsahh
@ceekay82
@DanielWeitenauer
@darwin26
@dennzimm
@dergel
@dtpop
@eaCe
@elricco
@Goldfischpeter
@gseilheimer
@IngoWinter
@NGWNGW
@olien
@phoebusryan
@polarpixel
@schuer
@skerbis
@tgoellner
@tyrant88

**Comment by eaCe** [comment]
Da eine Reaktion darauf ja keine notification wirft gebe ich hiermit eine +1 ;)

**Comment by alexwenz** [comment]
+1

**Comment by skerbis** [comment]
Ich schliße mich dem mit meinen bescheidenen Mitteln an. 👍

**Comment by olien** [comment]
+1

**Comment by schuer** [comment]
Ich schlage mal direkt das neue Multiupload-Addon für die erste Addon-Challenge vor. Das wurde bisher als erster Wurf umgesetzt und benötigt sicherlich noch etwas Pflege:

* In den Medienpool einhängen (aktuell ist es nur in der Sidebar)
* Ggfls ein anderer Unterbau, um flexibel und updatefähig zu bleiben (http://fineuploader.com)?
* Doku und Testing
* Umbenennung
* Vielleicht auch über clientseitiges Image-Resize nachdenken?
* Mehr Testing

**Comment by aeberhard** [comment]
+1

**Comment by skerbis** [comment]
- evtl. grundlegende Metainfos beim Upload mitgeben. bzw. wie in R4 direkt nach dem Upload.

**Comment by darwin26** [comment]
Addon-Challenge ... gern... helft mir mal eben, bitte ... wie soll das ablaufen? Ich fork das Teil und bring einfach meine Änderungen hier ran (bin kein github user (noch nicht) ) ... und jemand fügt es zusammen (oute mich gerade als github DAU :/) ... oder gibts da nen anderen Weg, damit wir uns da nicht zu sehr in die Quere kommen... Danke.

**Comment by skerbis** [comment]
@darwin26 

> Ich fork das Teil und bring einfach meine Änderungen hier ran 
genau so

**Comment by tbaddade** [comment]
@darwin26 Ist alles in der [Readme](https://github.com/FriendsOfREDAXO/Info#ein-repo-forken-um-einen-pull-request-zu-starten) beschrieben.

**Comment by darwin26** [comment]
ah.. habs ... und (sry) wo kann ich bei github das abstellen, das ich nicht jeden Kommentar von FOR/info per E-mail bekomme *grmpf* ... hab in die settings schon reingeschaut, aber ganz klar wars mir nicht... (sry) DANKE!

bekomm sogar meine eigenen (SPAM);)

**Comment by eaCe** [comment]
@darwin26 auf dein Icon oben rechts -> Settings -> Notifications.

Dort kannst du einstellen wie du diese bekommen möchtest

**Comment by alexplusde** [comment]
Ich hätte nichts einzuwenden, wenn wir im Oktober gleich mit dem Multiupload starten. 

Ich würde schauen, dass ich mich wie zuletzt bei yform oder search_it an der Doku beteilige.

**Comment by gharlan** [comment]
Bin bis 22.10. im Urlaub, aber ihr könnt natürlich trotzdem auch gerne ohne mich starten.

**Comment by DanielWeitenauer** [comment]
Ich wäre dabei, auch wenn Multiupload eine harte Challenge für mich ist. 
Einen Themen-Vorschlag dazu habe ich auch noch: Möglichkeit es im Frontend bzw. über YForm/Community einzubinden.

**Comment by alexplusde** [comment]
Frage hierzu noch @dergel: Was für Auswirkungen hätte das auf `multiupload`, wenn der Mediapool 3.0 kommt? Nicht, dass die Arbeit dann umsonst wäre.

**Comment by dergel** [comment]
bischen was wir dann ja ändern - z.b. mehrere Medienpools. Umsonst auf keinen Fall. Ist ja auch die Frage ob man das nicht später komplett integriert. (auch wenn es noch etwas dauern wird)

**Comment by gharlan** [comment]
> Ist ja auch die Frage ob man das nicht später komplett integriert.

Genau darum geht es ja. Meiner Meinung nach sollte der neue Medienpool zentral auf ein Multi-Upload-Feld setzen.

**Comment by dergel** [comment]
das wird sicher passieren, nur bis dahin wird es ja noch dauern, und ich denke es würde dann keinen stören, wenn wir das hier vorhandene dann mit einbauen. ich glaube umsonst ist die arbeit auf keinen fall. Aber klar - irgendwas wird eventuell hinten weg fallen. Ich kann das nicht genau beantworten.

**Comment by alexplusde** [comment]
Gut, also, dann wagen wir doch mal den Versuch für Oktober.

Issues und PR, die im Rahmen der Challenge eröffnet, bearbeitet und gemerged werden, sollten mit einem `(Challenge!)` versehen werden, damit die Aktion auch irgendwie messbar wird.

Es gibt einen optionalen offenen Slack-Channel: #for_challenge

**Comment by schuer** [comment]
Die Challenge hat irgendwie nicht geklappt, was? ;)
Aber egal, wir haben alle genug zu tun. Vielleicht klappt’s beim nächsten Mal.

Ich schließe das Issue, wenn’s euch recht ist. Falls nicht, bitte einfach wieder öffnen.
