### ISSUE TITLE
Doku und Hilfe: Doku-Dummy für FOR

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/Info#21]
Für `yform` hat @dergel ein Plugin erstellt, das als Basis dient, eine Doku/Hilfe zu einem Addon einzureichen. Auch die `search_it`-Doku basiert darauf. Der große Vorteil ist, dass die Doku Markup-basiert ist und sowohl auf GitHub, als auch innerhalb von Redaxo gut mit Querverlinkungen umgehen kann.

Ich würde mir wünschen, dass auch FOR-Addons auf diesen Zug aufspringen und eine Hilfe/Doku als Doku-Plugin mitliefern, sobald eine einfache ReadMe nicht ausreicht. Was meint ihr?
## 

Leider habe ich keine Ahnung, wie genau das Plugin angepasst werden muss und was ggf. am Addon noch eingestellt werden muss (z.B. automatische Doku-Plugin-Installation?). Auch weiß ich nicht, ob ich dafür einen extra Fork erstellen sollte oder doch lieber eine Branch, damit von Haus aus jeder in FOR an der Doku mitschreiben kann.

Falls also gewünscht, würde ich gerne einen Doku-Dummy im FOR Dummy-Addon sehen. Mit einer Kurzanleitung, wie der Workflow aussieht, um das Doku-Plugin in ein bestehendes Addon auf FOR zu integrieren. Von jemandem, der da besser Bescheid weiß als ich. :)

/cc @schuer @tyrant88 @dergel

**Comment by olien** [comment]
@aeberhard

**Comment by alexplusde** [comment]
@aeberhard gibt's Bestrebungen, den Dummy zu FOR zu übertragen? In jedem Fall werde ich das Issue mal schließen, da es ja nun eine Lösung gibt.

**Comment by aeberhard** [comment]
@alexplusde ja es gibt auch schon pull-requests fürs Demo-Addon
https://github.com/FriendsOfREDAXO/demo_addon/pulls
