### ISSUE TITLE
MyREDAXO-Account für FOR anlegen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/Info#3]
Siehe Diskussion in #2: Wir werden vorerst manuell veröffentlichen. Das Passwort für den Account tauschen wir untereinander aus, ohne es hier irgendwo zu hinterlegen.

Jemand müssten den FOR-Account anlegen, vermutlich am besten mit einer redaxo.org-E-Mailadresse.

**Comment by dergel** [comment]
ich kann die E-Mail Adresse anlegen.. nur wohin soll sie leiten ? Sollte jemand das vielleicht als FoR-Bürgermeister übernehmen ? Dirk, du ? :)

**Comment by schuer** [comment]
Bürgermeister, haha.
Lass sie doch am besten an euch Core-Leute leiten. Kannst mich gerne noch mit in den Verteiler stecken, dann kümmere ich mich um den myREDAXO-Account.

**Comment by schuer** [comment]
Ping :)

**Comment by schuer** [comment]
Vielleicht `friendsof@redaxo.org`? ;)

**Comment by ceekay82** [comment]
Finde ich gut

 

Von: Dirk Schürjohann [mailto:notifications@github.com] 
Gesendet: Montag, 23. Mai 2016 18:35
An: FriendsOfREDAXO/Info
Betreff: Re: [FriendsOfREDAXO/Info] MyREDAXO-Account für FOR anlegen (#3)

 

Ping :)
