### ISSUE TITLE
Wer ist für ein Addon "verantwortlich"

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/Info#4]
Hier: evtl alle.
Bei der aktuellen Menge der Addons  / Entwickler weiß natürlich jeder wer was gemacht hat.
Was ist wenn es mehr wird? Sollen wir in der package.yml noch einen primären "Ansprechpartner" oder so etwas hinterlegen?

z.B.: 

author: Friends Of REDAXO (Ansprechpartner für dieses Addon: https://github.com/olien)

- habt Ihr besserer Ideen?
- ist unnötig...

LG
Oliver

**Comment by phoebusryan** [comment]
Nein, da bin ich absolut dafür. Sowas in die Package zu setzen wäre nur dann sinnvoll, wenn es auch im Installer angezeigt wird. Wenn jemand einen Bug findet, weiss er sonst nicht wirklich, wen er darauf ansprechen soll. Häufig gehen die Leute ja direkt auf einem zu statt ein Issue zu schreiben.

**Comment by schuer** [comment]
Meine Meinung: Ich würde `author` immer nur auf `Friends Of REDAXO` setzen, weil es den Grundgedanken unterstützt, dass die Arbeit aller Beteiligten gleichwertig ist. Ich würde stattdessen ein weiteres Feld einfügen, das z. B. `team lead` heißen könnte und angibt, wer das Addon aktuell »anführt«.

(Alternativ könnte man sowas auch unten in die README schreiben.)

**Comment by polarpixel** [comment]
Gute Idee! Wir hatten diese Diskussion ja auch schon.

**Comment by olien** [comment]
@polarpixel Und wie ist die Diskussion ausgegangen?

Ich finde Dirks Vorschlag gut (neues Feld & evtl. README)

**Comment by polarpixel** [comment]
Ja, Dirk schlug genau das vor, was er auch jetzt schrieb.

**Comment by olien** [comment]
Dann machen wir es so wenn keiner etwas dagegen hat!

**Comment by gharlan** [comment]
Schließe mich @schuer an (mal wieder), bzgl. author.
Wegen mir brauchen wir den primären Ansprechpartner allerdings eigentlich nirgends festhalten. Man soll einfach hier auf github Issues anlegen, dann wird er sich schon melden.
Aber scheint die Mehrheit hier ja anders zu sehen, für mich auch ok.
Sollte mal jemand ein Addon nicht weiter entwickeln, muss man sich dann halt überlegen, ab wann er nicht mehr der primäre Ansprechpartner ist etc. Das würde man vermeiden, wenn man es gar nicht erst "offiziell" festhält.

**Comment by schuer** [comment]
Was @gharlan sagt.

**Comment by gharlan** [comment]
Könnten auch statt den Namen des primären Entwicklers zu nennen, grundsätzlich diesen Link in die Readme setzen: https://github.com/FriendsOfREDAXO/aufgaben/graphs/contributors
Dort sieht man gut, wer insgesamt, bzw. aktuell wohl die Hauptentwickler sind.
