### ISSUE TITLE
Addon: Suche/Search

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/Info#8]
_From @schuer on May 22, 2016 17:56_

REDAXO 5 benötigt noch eine Suche. Es gibt aktuell verschiedene Vorschläge oder Ansätze:
- RexSearch wird von @xong eventuell für R5 entwickelt
- @phoebusryan möchte vielleicht einen Crawler bauen
- Auf Basis von @tbaddade s Watson könnte eine schlichte Suche fürs Frontend gebaut werden
- Eine Anregung für eine simple Suche hat @tbaddade mal in ein [Gist](https://gist.github.com/tbaddade/575ddf218ba2b733caa30292c354ce38) gesteckt

Vielleicht könnten die verschiedenen Kräfte hier bei FOR gebündelt und eine Suche entwickelt werden.

_Copied from original issue: FriendsOfREDAXO/wuensche_ideen#4_

**Comment by schuer** [comment]
_From @phoebusryan on May 23, 2016 6:26_

Ich hatte schon ein paar Stunden in meinen rex_sphider investiert und hatte auch schon viele Zeilen gecodet aber aufgrund der Aussage von @xong (er würde rex_search bis Ende Mai portieren) habe ich das Projekt eingestellt, da ich absolut gegen Parallelentwicklung und Manpowerverschwendung bin.

**Comment by schuer** [comment]
_From @olien on May 23, 2016 7:20_

Ideen

- Berücksichtigung von TableManager Tabellen
- Berücksichtigung der Community Berechtigungen
- PDFs berücksichtigen

**Comment by schuer** [comment]
_From @phoebusryan on May 23, 2016 8:59_

Mein Sphider wird PDFs berücksichtigen, Tabellen aber nicht. Geschützte Bereiche sicher in einem zweiten Schritt.

Edit: Gemäss der Diskussion in rex_radio werde ich das Projekt demnächst wieder aufnehmen.

**Comment by schuer** [comment]
_From @alexplusde on June 4, 2016 12:15_

Mir wären Auswertungen sehr wichtig, um mehr über die Erwartungen der Nutzer zu erfahren.

In rex_search wurde bspw. gezeigt, welche die häufigsten Suchbegriffe waren und ob Treffer für den Begriff vorhanden sind.

Außerdem ergänzend zu @olien: 

- Cronjobs, automatische Aktualisierung des Suchindex, wenn sich Tabelleninhalte von yform ändern.
- Basis-Klassen fürs Froentend (z. B. Suchergebnis-Paginierung)

**Comment by alexplusde** [comment]
Portierung von `RexSearch für Redaxo 4` zu `Search it für Redaxo 5`
https://github.com/tyrant88/search_it/

* Volltextsuche
* Ähnlichkeitssuche (derzeit noch offene Issues)
* Automatische De-, Re- und Neu-Indexierung (derzeit noch offene Issues)
* Cronjobs (Anleitung als Howto)
* Datenbank-Suche
* Medienpool-Suche (derzeit noch offene Issues)
* PDF-Volltextsuche
* Dateiverezeichnis-Suche (Tests benötigt)
* Doku (derzeit noch offene Issues im Bereich Demo-Module, Howtos und Klassenreferenz)
* Search Higlighter
* Paginierung (kommt mind. als Howto)
* Statistik

Hilfe benötigt:
* Berücksichtigung von geschützten Bereichen
* o.g. Offene Issues

@lus hat zugesichert, das Projekt auf FOR zu stellen, wenn es vorzeigbar ist.

**Comment by alexplusde** [comment]
Der ursprüngliche Thread hat sich m.E. erledigt. Es gibt ein funktionierendes Such-Addon für Redaxo.
